name: Java CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 8
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: adopt
      - name: Build with Maven
        run: mvn package --file pom.xml